baseURL = "/"
languageCode = "en-us"
title = "The Stanford Basic Income Lab"
theme = "base-hugo-theme"
googleAnalytics = ""
paginate = 5

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[markup.goldmark.renderer]
unsafe = true

[params]
  # google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true
  paginage=5
  dateFormat = "January 2, 2006"

# main menu

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  parent = "About"
  name = "What is BIL?"
  url = "/about/what-is-bil"
  weight = 1

[[menu.main]]
  parent = "About"
  name = "What is UBI?"
  url = "/about/what-is-ubi"
  weight = 2

[[menu.main]]
  parent = "About"
  name = "People"
  url = "/about/people"
  weight = 3

[[menu.main]]
  name = "Events"
  url = "/events/"
  weight = 3

[[menu.main]]
  parent = "Events"
  name = "Upcoming"
  url = "/events/upcoming/"
  weight = 1

[[menu.main]]
  parent = "Events"
  name = "Past"
  url = "/events/past/"
  weight = 2

[[menu.main]]
  parent = "Events"
  name = "Videos"
  url = "/events/videos/"
  weight = 3

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 5

[[menu.main]]
  parent = "Research"
  name = "Research Visualization"
  url = "/research/ubi-visualization"
  weight = 4

[[menu.main]]
  parent = "Research"
  name = "Papers"
  url = "/research/papers"
  weight = 3  

[[menu.main]]
  parent = "Research"
  name = "Experiments Map"
  url = "/research/experiments-map"
  weight = 1

[[menu.main]]
  name = "Fellowships"
  url = "/fellowships"
  weight = 6

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 7

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 9

[[menu.main]]
  parent = "News"
  name = "COVID-19-Digest"
  url = "/covid-19-digest/"
  weight = 1

[[menu.main]]
  parent = "News"
  name = "In the News"
  url = "/news/"
  weight = 2

[[menu.main]]
  parent = "News"
  name = "Updates from the Lab"
  url = "/news/lab-updates/"
  weight = 3

[[menu.main]]
  parent = "News"
  name = "Newsletters"
  url = "/news/newsletters/"
  weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

# Assets needed
# -------------
# * Dark color menu button icon
