baseURL = "/"
languageCode = "en-us"
title = "Stanford Basic Income Lab"
theme = "base-hugo-theme"
googleAnalytics = ""
paginate = 5

[imaging]
resampleFilter = "box"
quality = 70
anchor = "smart"

[params]
  # google_analytics_id=""
  hideFooter=false
  includeBootstrapJs=true
  containerMaxWidth=1200
  showActiveNav=true
  paginage=5
  offline=false # default = false

# main menu

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 2

[[menu.main]]
    parent = "About"
	name = "What is BIL?"
	url = "/about/what-is-bil"
    weight = 1

[[menu.main]]
    parent = "About"
	name = "What is Basic Income?"
	url = "/about/what-is-ubi"
    weight = 2

[[menu.main]]
    parent = "About"
	name = "People"
	url = "/about/people"
    weight = 3

[[menu.main]]
  name = "Events"
  url = "/events/"
    weight = 3

[[menu.main]]
    parent = "Events"
	name = "Upcoming"
	url = "/events/upcoming/"
    weight = 1  

[[menu.main]]
    parent = "Events"
	name = "Past"
	url = "/events/past/"
    weight = 2   

[[menu.main]]
    parent = "Events"
	name = "Videos"
	url = "/events/videos/"
    weight = 3


[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 5

[[menu.main]]
    parent = "Research"
	name = "Mapping UBI Research"
	url = "/research/mapping-ubi-research"
    weight = 1

[[menu.main]]
    parent = "Research"
	name = "UBI Cities Toolkit"
	url = "/research/ubi-cities-toolkit"
    weight = 2

[[menu.main]]
    parent = "Research"
	name = "Basic Income Experiments"
	url = "/research/basic-income-experiments"
    weight = 3

[[menu.main]]
    name = "Positions"
    url = "/positions/graduate-fellowships"
    weight = 6

[[menu.main]]
    parent = "Positions"
	name = "Graduate Fellowships"
	url = "/positions/graduate-fellowships/"
    weight = 1

[[menu.main]]
    parent = "Positions"
	name = "Postdoctoral Research Fellow"
	url = "/positions/postdoctoral-research-fellow/"
    weight = 2

[[menu.main]]
    parent = "Positions"
	name = "Undergraduate Opportunities"
	url = "/positions/undergrad-opportunities/"
    weight = 3

[[menu.main]]
    name = "Courses"
    url = "/courses/"
    weight = 7


[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 9

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

# Assets needed
# -------------
# * Dark color menu button icon
