[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[build.environment]
  TZ = "America/New_York"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/about"
  to = "/about/what-is-bil"
  status = 301
  force=true

[[redirects]]
from = "/research"
  to = "/research/mapping-ubi-research"
  status = 301
  force=true

[[redirects]]
from = "/events"
  to = "/events/upcoming"
  status = 301
  force=true

[[redirects]]
from = "/about/what-basic-income"
  to = "/about/what-is-ubi/"
  status = 301
  force=true

[[redirects]]
from = "/about/people/leadership"
  to = "/about/people/"
  status = 301
  force=true

[[redirects]]
from = "/about/people/current-graduate-fellows"
  to = "/about/people/"
  status = 301
  force=true

[[redirects]]
from = "/about/people/jos-luis-sabau"
  to = "/about/people/"
  status = 301
  force=true

[[redirects]]
from = "/about/people/juliana-bidadanure"
  to = "/about/people/"
  status = 301
  force=true

[[redirects]]
from = "/about/people/former-graduate-fellows"
  to = "/about/people/"
  status = 301
  force=true

[[redirects]]
from = "/about/location-and-contact"
  to = "/about/what-is-bil"
  status = 301
  force=true

[[redirects]]
from = "/events/upcoming-events"
  to = "/events/upcoming"
  status = 301
  force=true

[[redirects]]
from = "/events/past-events"
  to = "/events/past"
  status = 301
  force=true

[[redirects]]
from = "/events/our-videos"
  to = "/events/videos/"
  status = 301
  force=true

[[redirects]]
from = "/courses/search"
  to = "/courses"
  status = 301
  force=true

[[redirects]]
from = "/get-involved/join-mailing-list"
  to = "/"
  status = 301
  force=true

[[redirects]]
from = "/get-involved/giving"
  to = "/"
  status = 301
  force=true

[[redirects]]
from = "/fellowships/postdoctoral-research-fellow"
  to = "/fellowships/postdoctoral-fellow"
  status = 301
  force=true

[[redirects]]
from = "/research/ubi-cities-toolkit/"
  to = "/research/papers/ubi-cities-toolkit/"
  status = 301
  force=true  
