backend:
  name: git-gateway
  branch: cms-dev # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  #HOMEPAGE
  - label: "Home"
    name: home
    preview_path: /
    files:
        - label: Homepage Content
          name: homepage_content
          file: "data/home/whatWeDo.yaml"
          extension: "yaml"
          fields:
            - {label: Hero panel heading, name: heading, widget: string}
            - {label: Hero panel paragraph 1, name: p1, widget: string}
            - {label: Hero panel paragraph 2, name: p2, widget: string}
            - {label: Hero panel paragraph 3, name: p3, widget: string}
            - {label: Hero panel call to action, name: cta, widget: string}
            - {label: What is Basic Income panel heading, name: heading2, widget: string}
            - {label: What is Basic Income panel subheading, name: subhead2, widget: string}
            - {label: Item 1 heading, name: item1Head, widget: string}
            - {label: Item 1 Text, name: item1Text, widget: string}
            - {label: Item 2 heading, name: item2Head, widget: string}
            - {label: Item 2 Text, name: item2Text, widget: string}
            - {label: Item 3 heading, name: item3Head, widget: string}
            - {label: Item 3 Text, name: item3Text, widget: string}
            - {label: Item 4 heading, name: item4Head, widget: string}
            - {label: Item 4 Text, name: item4Text, widget: string}
            - {label: Item 5 heading, name: item5Head, widget: string}
            - {label: Item 5 Text, name: item5Text, widget: string}
            - {label: Call to action, name: cta2, widget: string}
            - {label: Visualization teaser heading, name: heading3, widget: string}
            - {label: Visualization teaser subtext, name: subhead3, widget: string}
            - {label: Call to action, name: cta3, widget: string}
            - {label: Recent news heading, name: heading4, widget: string}
            
  #WHAT IS BIL PAGE
  - label: "What is BIL?"
    name: what_is_bil
    preview_path: about/what-is-bil/
    files:
        - label: What is BIL Page Content
          name: what_is_bil_content
          file: "content/about/what-is-bil/_index.md"
          extension: "md"
          fields:
            - {label: pageTitle, name: title, widget: hidden, default: "What Is BIL"}
            - {label: layout, name: layout, widget: hidden, default: "what-is-bil"}
            - {label: Hero Image Text, name: herotext, widget: string}
            - {label: Panel 1 Heading, name: heading1, widget: string}
            - {label: Panel 1 Body text, name: body1, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 2 Heading, name: heading2, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 2 Paragraph 1, name: p2p1, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 2 Paragraph 2, name: p2p2, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 2 Paragraph 3, name: p2p3, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 3 Heading, name: heading3, widget: string}
            - {label: Panel 3 Body Text, name: body3, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 4 Heading, name: heading4, widget: string}
            - {label: Panel 4 Body Text, name: body4, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 5 Heading, name: heading5, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 5 Paragraph 1, name: p5p1, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 5 Paragraph 2, name: p5p2, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 5 Paragraph 3, name: p5p3, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 5 Paragraph 4, name: p5p4, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Sponsors Panel Heading, name: heading6, widget: string}
            - {label: Panel 6 Body Text, name: body6, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}

  #WHAT IS UBI PAGE
  - label: "What is UBI?"
    name: what_is_ubi
    preview_path: about/what-is-ubi/
    files:
        - label: What is UBI Page Content
          name: what_is_ubi_content
          file: "content/about/what-is-ubi/_index.md"
          extension: "md"
          fields:
            - {label: pageTitle, name: title, widget: hidden, default: "What Is UBI"}
            - {label: layout, name: layout, widget: hidden, default: "what-is-ubi"}
            - {label: Hero Image Text, name: herotext, widget: string}
            - {label: Panel 1 Heading, name: heading1, widget: string}
            - {label: Panel 1 Body text, name: body1, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 2 Heading, name: heading2, widget: string}
            - {label: Panel 2 Body text, name: body2, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
            - {label: Panel 3 heading, name: heading3, widget: string}
            - {label: Panel 3 subheading, name: subhead3, widget: string}
            - {label: Item 1 heading, name: item1head, widget: string}
            - {label: Item 1 Text, name: item1text, widget: string}
            - {label: Item 2 heading, name: item2head, widget: string}
            - {label: Item 2 Text, name: item2text, widget: string}
            - {label: Item 3 heading, name: item3head, widget: string}
            - {label: Item 3 Text, name: item3text, widget: string}
            - {label: Item 4 heading, name: item4head, widget: string}
            - {label: Item 4 Text, name: item4text, widget: string}
            - {label: Item 5 heading, name: item5head, widget: string}
            - {label: Item 5 Text, name: item5text, widget: string}

  #PEOPLE PAGE
  - label: "People"
    name: people
    preview_path: about/people/
    files:
        - label: Pics & Bios
          name: bios
          file: "data/people/all.yaml"
          extension: "yaml"
          fields:
            label: Members
            name: personnel
            widget: list
            fields:
            - {label: Name, name: name, widget: string}
            - {label: Role, name: role, widget: select, options: ["Leadership","Fellow","Former"]}
            - {label: Title, name: title, widget: string}
            - {label: Full image, name: image, widget: image}
            - {label: Thumbnail image, name: thumb, widget: image}
            - {label: Status, name: current, widget: hidden, default: true}
            - {label: Bio, name: blurb, widget: markdown, buttons: [bold, italic, link, bulleted-list, numbered-list]}
                  
            

        